package com.es2.infoget.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CursosAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursosAllPropertiesEquals(Cursos expected, Cursos actual) {
        assertCursosAutoGeneratedPropertiesEquals(expected, actual);
        assertCursosAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursosAllUpdatablePropertiesEquals(Cursos expected, Cursos actual) {
        assertCursosUpdatableFieldsEquals(expected, actual);
        assertCursosUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursosAutoGeneratedPropertiesEquals(Cursos expected, Cursos actual) {
        assertThat(expected)
            .as("Verify Cursos auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursosUpdatableFieldsEquals(Cursos expected, Cursos actual) {
        assertThat(expected)
            .as("Verify Cursos relevant properties")
            .satisfies(e -> assertThat(e.getNomecurso()).as("check nomecurso").isEqualTo(actual.getNomecurso()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursosUpdatableRelationshipsEquals(Cursos expected, Cursos actual) {
        // empty method
    }
}
