package com.es2.infoget.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CursoDisciplinaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoDisciplinaAllPropertiesEquals(CursoDisciplina expected, CursoDisciplina actual) {
        assertCursoDisciplinaAutoGeneratedPropertiesEquals(expected, actual);
        assertCursoDisciplinaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoDisciplinaAllUpdatablePropertiesEquals(CursoDisciplina expected, CursoDisciplina actual) {
        assertCursoDisciplinaUpdatableFieldsEquals(expected, actual);
        assertCursoDisciplinaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoDisciplinaAutoGeneratedPropertiesEquals(CursoDisciplina expected, CursoDisciplina actual) {
        assertThat(expected)
            .as("Verify CursoDisciplina auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoDisciplinaUpdatableFieldsEquals(CursoDisciplina expected, CursoDisciplina actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCursoDisciplinaUpdatableRelationshipsEquals(CursoDisciplina expected, CursoDisciplina actual) {
        assertThat(expected)
            .as("Verify CursoDisciplina relationships")
            .satisfies(e -> assertThat(e.getCursos()).as("check cursos").isEqualTo(actual.getCursos()))
            .satisfies(e -> assertThat(e.getDisciplinas()).as("check disciplinas").isEqualTo(actual.getDisciplinas()));
    }
}
