package com.es2.infoget.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisciplinasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinasAllPropertiesEquals(Disciplinas expected, Disciplinas actual) {
        assertDisciplinasAutoGeneratedPropertiesEquals(expected, actual);
        assertDisciplinasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinasAllUpdatablePropertiesEquals(Disciplinas expected, Disciplinas actual) {
        assertDisciplinasUpdatableFieldsEquals(expected, actual);
        assertDisciplinasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinasAutoGeneratedPropertiesEquals(Disciplinas expected, Disciplinas actual) {
        assertThat(expected)
            .as("Verify Disciplinas auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinasUpdatableFieldsEquals(Disciplinas expected, Disciplinas actual) {
        assertThat(expected)
            .as("Verify Disciplinas relevant properties")
            .satisfies(e -> assertThat(e.getNomedisciplina()).as("check nomedisciplina").isEqualTo(actual.getNomedisciplina()))
            .satisfies(e -> assertThat(e.getCargahoraria()).as("check cargahoraria").isEqualTo(actual.getCargahoraria()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinasUpdatableRelationshipsEquals(Disciplinas expected, Disciplinas actual) {
        assertThat(expected)
            .as("Verify Disciplinas relationships")
            .satisfies(e -> assertThat(e.getProfessores()).as("check professores").isEqualTo(actual.getProfessores()));
    }
}
