package com.es2.infoget.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotasAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotasAllPropertiesEquals(Notas expected, Notas actual) {
        assertNotasAutoGeneratedPropertiesEquals(expected, actual);
        assertNotasAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotasAllUpdatablePropertiesEquals(Notas expected, Notas actual) {
        assertNotasUpdatableFieldsEquals(expected, actual);
        assertNotasUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotasAutoGeneratedPropertiesEquals(Notas expected, Notas actual) {
        assertThat(expected)
            .as("Verify Notas auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotasUpdatableFieldsEquals(Notas expected, Notas actual) {
        assertThat(expected)
            .as("Verify Notas relevant properties")
            .satisfies(e -> assertThat(e.getNota()).as("check nota").isEqualTo(actual.getNota()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotasUpdatableRelationshipsEquals(Notas expected, Notas actual) {
        assertThat(expected)
            .as("Verify Notas relationships")
            .satisfies(e -> assertThat(e.getAlunos()).as("check alunos").isEqualTo(actual.getAlunos()))
            .satisfies(e -> assertThat(e.getDisciplinas()).as("check disciplinas").isEqualTo(actual.getDisciplinas()));
    }
}
